# Generated by Django 3.2.7 on 2021-09-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accuracyModel',
            fields=[
                ('model_id', models.IntegerField(db_column='model_id', primary_key=True, serialize=False)),
                ('accuracy', models.IntegerField()),
            ],
            options={
                'db_table': 'accuracy',
            },
        ),
        migrations.CreateModel(
            name='newsModel',
            fields=[
                ('news_id', models.IntegerField(db_column='news_id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=20000)),
                ('summary', models.CharField(max_length=500)),
                ('registrant', models.CharField(max_length=18)),
                ('press', models.CharField(max_length=18)),
                ('registration_date', models.DateField()),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='stockModel',
            fields=[
                ('stock_name', models.CharField(max_length=20)),
                ('stock_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stock_category', models.CharField(max_length=20)),
                ('stock_foundation_year', models.DateField()),
                ('stock_listing_date', models.DateField()),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='sentimentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('news_id', models.ForeignKey(db_column='news_id', on_delete=django.db.models.deletion.CASCADE, to='stock.newsmodel')),
            ],
            options={
                'db_table': 'sentiment',
            },
        ),
        migrations.CreateModel(
            name='priceModel',
            fields=[
                ('stock_id', models.IntegerField(db_column='stock_id', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('volume', models.IntegerField()),
                ('stock_code', models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, to='stock.stockmodel')),
            ],
            options={
                'db_table': 'price',
            },
        ),
        migrations.CreateModel(
            name='predictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('model_id', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, to='stock.accuracymodel')),
                ('stock_id', models.ForeignKey(db_column='stock_id', on_delete=django.db.models.deletion.CASCADE, to='stock.pricemodel')),
            ],
            options={
                'db_table': 'predict',
            },
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='stock_code',
            field=models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, to='stock.stockmodel'),
        ),
        migrations.AddField(
            model_name='accuracymodel',
            name='stock_code',
            field=models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, to='stock.stockmodel'),
        ),
    ]
