# Generated by Django 3.2.6 on 2021-08-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.IntegerField()),
                ('stock_name', models.CharField(max_length=20)),
                ('stock_code', models.IntegerField()),
                ('stock_category', models.CharField(max_length=20)),
                ('stock_market_capitalization', models.IntegerField()),
                ('stock_foundation_year', models.IntegerField()),
                ('stock_listing_date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
