# Generated by Django 3.2.7 on 2021-09-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricemodel',
            name='adj_close',
        ),
    ]
