# Generated by Django 3.2.6 on 2021-08-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'my_user',
            },
        ),
    ]
